package com.fitness.mailservice.service;

import com.fitness.mailservice.DTO.RecommendationGeneratedEvent;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    public void sendRecommendationEmail(
            RecommendationGeneratedEvent event) {

        try {
            MimeMessage message = mailSender.createMimeMessage();

            MimeMessageHelper helper =
                    new MimeMessageHelper(message, true, "UTF-8");

            helper.setTo(event.getEmail());

            helper.setSubject("Your AI Fitness Recommendation");

            helper.setText(
                    buildEmailContent(event),
                    true
            );

            mailSender.send(message);

            log.info(
                    "Recommendation email sent successfully to {}",
                    event.getEmail()
            );

        } catch (MessagingException e) {

            log.error(
                    "Failed to send recommendation email to {}",
                    event.getEmail(),
                    e
            );

            throw new RuntimeException(
                    "Failed to send recommendation email", e
            );
        }
    }

    private String buildEmailContent(
            RecommendationGeneratedEvent event) {

        return """
                <html>
                <body>

                <h2>Your AI Fitness Recommendation</h2>

                <p>Hello!</p>

                <p>
                Here is your personalized analysis
                based on your latest activity.
                </p>

                <h3>Activity Analysis</h3>

                <p><b>Overall:</b> %s</p>
                <p><b>Pace:</b> %s</p>
                <p><b>Heart Rate:</b> %s</p>
                <p><b>Calories Burned:</b> %s</p>

                <h3>Improvements</h3>

                %s

                <h3>Suggested Workouts</h3>

                %s

                <h3>Safety</h3>

                %s

                <hr>

                <p>
                Generated by your AI Fitness Assistant.
                </p>

                </body>
                </html>
                """.formatted(
                event.getAnalysis().getOverall(),
                event.getAnalysis().getPace(),
                event.getAnalysis().getHeartRate(),
                event.getAnalysis().getCaloriesBurned(),
                buildImprovements(event),
                buildSuggestions(event),
                buildSafety(event)
        );
    }


    // ============================
    // Improvements
    // ============================

    private String buildImprovements(
            RecommendationGeneratedEvent event) {

        if (event.getImprovements() == null ||
                event.getImprovements().isEmpty()) {

            return "<p>No specific improvements were identified.</p>";
        }

        StringBuilder html = new StringBuilder("<ul>");

        event.getImprovements().forEach(improvement -> {

            html.append("<li>")
                    .append("<strong>")
                    .append(improvement.getArea())
                    .append("</strong>: ")
                    .append(improvement.getRecommendation())
                    .append("</li>");
        });

        html.append("</ul>");

        return html.toString();
    }


    // ============================
    // Suggestions
    // ============================

    private String buildSuggestions(
            RecommendationGeneratedEvent event) {

        if (event.getSuggestions() == null ||
                event.getSuggestions().isEmpty()) {

            return "<p>No workout suggestions available.</p>";
        }

        StringBuilder html = new StringBuilder("<ul>");

        event.getSuggestions().forEach(suggestion -> {

            html.append("<li>")
                    .append("<strong>")
                    .append(suggestion.getWorkout())
                    .append("</strong>: ")
                    .append(suggestion.getDescription())
                    .append("</li>");
        });

        html.append("</ul>");

        return html.toString();
    }


    // ============================
    // Safety
    // ============================

    private String buildSafety(
            RecommendationGeneratedEvent event) {

        if (event.getSafety() == null ||
                event.getSafety().isEmpty()) {

            return "<p>No specific safety recommendations.</p>";
        }

        StringBuilder html = new StringBuilder("<ul>");

        event.getSafety().forEach(safety -> {

            html.append("<li>")
                    .append(safety)
                    .append("</li>");
        });

        html.append("</ul>");

        return html.toString();
    }
}
